### ISSUE TITLE
Publish changes

### ISSUE THREAD

**Issue by themeteorchef** [siteleaf/siteleaf-api#9]
Is it possible to trigger the Publish Changes command via the API? Would be nice to automate the "click" of that button.

Also: is this still being actively maintained?

**Comment by sskylar** [comment]
Not at the moment, but totally agree — adding a publish endpoint to our API is on the roadmap. 

Regarding maintenance, this repo is updated only on API changes. We'll make sure to update once a publish endpoint is available. Feel free to reach team@siteleaf.com if we can help with anything else!
